#!/usr/bin/env python3
"""Step 1: extract the most-recent visible assistant response text per task.

SCOPE CAVEAT — read before using this anywhere else in the quality module.
What we recover is the LAST assistant `message` item present in a task's
`input` — i.e. the most recent turn visible at the moment this call was
logged. It is NOT proof that:
  (a) this is the task's true FINAL response — the task may continue in a
      later call not present in this export chunk (every reconstructed
      trajectory here is exactly one call — see load_trajectories.py); or
  (b) this text was generated BY the request we're pricing — the export
      never includes any call's own output (AGENTS.md: "There is no output
      field"). Under the one-model-per-trajectory premise, it WAS produced
      by the same model listed in `model`, just on an earlier, unlogged turn
      of the same task.

Verified against the real export (see Step 0 discussion before this file was
written): recoverability is NOT uniform across model families.
  - Claude-served tasks: 755/755 (100%) have non-empty final-message text.
  - GPT-served tasks: 238/245 (97%) have an EMPTY final message. This is
    structural, not missing data — GPT-family turns very often end with a
    tool call (e.g. apply_patch) followed by an essentially-blank closing
    message item, with no natural-language text attached.
Callers MUST treat has_response_text=False as "not scorable", never as a bad
(empty) response — quality_heuristics.py skips these entirely rather than
penalizing them, per an explicit decision to avoid baking in a family bias
that has nothing to do with actual quality.

Usage: python rule_based_router/quality/extract_response.py export/ [out.jsonl]
Importable: extract_response(call) -> dict; extract_all(export_dir) -> list[dict]
"""
import json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
from load_trajectories import iter_requests, group_trajectories  # noqa: E402

def _message_text(item):
    c = item.get("content")
    if isinstance(c, str): return c
    if isinstance(c, list): return " ".join(p.get("text", "") for p in c if p.get("type") == "input_text")
    return ""

def extract_response(call):
    """Return {"model": str, "has_response_text": bool, "response_text": str}
    for the most-recent visible assistant message in this call's input. See
    module docstring for exactly what this text does and doesn't represent."""
    items = call["input"]
    last_msg = next((it for it in reversed(items)
                      if it.get("role") == "assistant" and it.get("type") in ("message", None)), None)
    text = _message_text(last_msg) if last_msg else ""
    return {
        "model": call["model"],
        "has_response_text": bool(text.strip()),
        "response_text": text,
    }

def extract_all(export_dir):
    groups = group_trajectories(r for _, _, r in iter_requests(export_dir))
    rows = []
    for key, calls in groups.items():
        last_call = calls[-1]  # every trajectory here is one call, but stay generic for future chunks
        row = extract_response(last_call)
        row["trajectory_id"] = key
        rows.append(row)
    return rows

def main():
    export = sys.argv[1] if len(sys.argv) > 1 else "export"
    out_path = sys.argv[2] if len(sys.argv) > 2 else str(Path(__file__).resolve().parent.parent / "results" / "responses.jsonl")
    rows = extract_all(export)
    Path(out_path).parent.mkdir(exist_ok=True, parents=True)
    with open(out_path, "w") as f:
        for r in rows: f.write(json.dumps(r) + "\n")

    n = len(rows)
    n_with_text = sum(r["has_response_text"] for r in rows)
    by_family = {}
    for r in rows:
        fam = "claude" if r["model"].startswith("claude") else "gpt"
        by_family.setdefault(fam, [0, 0])
        by_family[fam][0] += 1
        by_family[fam][1] += r["has_response_text"]

    print(f"tasks={n}  with_recoverable_response_text={n_with_text} ({n_with_text/n:.1%})")
    for fam, (total, withtext) in sorted(by_family.items()):
        print(f"  {fam:8s} {withtext}/{total} ({withtext/total:.1%}) have recoverable text")
    print("NOTE: recovered text is the most-recent VISIBLE assistant turn, not proven to be the")
    print("      task's true final response, and not this call's own generated output — see")
    print("      module docstring. Tasks with has_response_text=False are NOT scorable and must")
    print("      be excluded from quality stats, not treated as empty/bad responses.")
    print(f"wrote {out_path}")

if __name__ == "__main__": main()
