#!/usr/bin/env python3
"""Tiny local demo UI: type a task, see which model the real router picks and
why. Styled to match the team's own Viktor-deck palette (templates/presentation.html).

Stdlib only, no framework. Calls feature_extraction.py and router.py
UNMODIFIED on a synthetic call built from the form input, so this can never
drift from what the router actually does.

WHY THE CHECKBOXES EXIST (read before demoing): the router's strongest signals
— a stakes tool actually called, a tool failure, a retry loop — describe things
that happen DURING a task's execution. A bare prompt literally cannot contain
them yet; they aren't hidden in the wording, they're generated by the agent's
later actions. So they can never be computed FROM the prompt the way the real
router computes them from real history. What CAN read straight from the prompt,
automatically, with no checkbox: the keyword-based starting tier (low/high-
stakes wording) — that already happens on every submit.

The checkboxes build real synthetic function_call / function_call_output /
reasoning items so the genuine feature-extraction code has something to detect
for the other signals. As a convenience, the page also SUGGESTS checkbox states
from simple keyword matches in your prompt as you type — clearly labelled as a
suggestion to verify, never presented as the real signal, so the demo never
overstates what it actually detected.

Run:    python3 validation/router_ui.py
Then:   open http://localhost:8787
"""
import html, sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from urllib.parse import parse_qs

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "rule_based_router" / "scripts"))
from feature_extraction import extract_features  # noqa: E402
from router import route_call, LADDER  # noqa: E402

PORT = 8787
LARGE_PAD_CHARS = 145_000  # pushes cumulative_input_tokens_est past router.LARGE_INPUT_TOKENS
FLAGS = ("stakes", "failed", "retry", "reasoning", "large", "resumed_wait")

FLAG_LABEL = {
    "stakes": "A stakes tool was called (delete / pay / publish / …)",
    "failed": "Most recent tool result looked like an error",
    "retry": "Stuck retrying the same tool call",
    "reasoning": "Earlier turns used step-by-step reasoning (GPT-style)",
    "large": "Unusually large accumulated context",
    "resumed_wait": "Just resumed from a background-wait check",
}

def build_call(prompt, stakes, failed, retry, reasoning, large, resumed_wait):
    sys_text = "You are Viktor, an autonomous AI coworker."
    if large:
        sys_text += "x" * LARGE_PAD_CHARS
    items = [
        {"type": "message", "role": "system", "content": sys_text},
        {"type": "message", "role": "user", "content": [{"type": "input_text", "text": prompt}]},
    ]
    if reasoning:
        items.append({"type": "reasoning", "id": "r1", "summary": [{"type": "summary_text", "text": "thinking"}]})
    if retry:
        for i in range(3):
            items.append({"type": "function_call", "name": "bash", "call_id": f"retry{i}", "arguments": '{"command":"ls /work"}'})
            items.append({"type": "function_call_output", "call_id": f"retry{i}", "output": '{"content":"same","exit_code":0}'})
    if stakes:
        items.append({"type": "function_call", "name": "delete_record", "call_id": "s1", "arguments": "{}"})
        items.append({"type": "function_call_output", "call_id": "s1", "output": '{"success":true}'})
    if resumed_wait:
        items.append({"type": "function_call", "name": "wait_for_background_work", "call_id": "w1", "arguments": "{}"})
        items.append({"type": "function_call_output", "call_id": "w1", "output": '{"wake_reason":"condition_met"}'})
    if failed:
        items.append({"type": "function_call", "name": "bash", "call_id": "e1", "arguments": '{"command":"do_thing"}'})
        items.append({"type": "function_call_output", "call_id": "e1", "output": '{"content":"","exit_code":1}'})
    items.append({"type": "message", "role": "assistant", "content": [{"type": "input_text", "text": ""}]})
    return {"model": "unknown", "input": items, "tools": []}

def route(prompt, **flags):
    call = build_call(prompt, **flags)
    feats = extract_features("ui", [call])[0]
    model, rules = route_call(feats)
    return model, rules

PAGE = """<!doctype html><html><head><meta charset="utf-8">
<title>Router demo</title>
<style>
  :root {{
    --ink: #0d0d1a;
    --indigo: #150079;
    --accent: #6748FD;
    --peach: #FFBD9E;
    --surface: #fbfaff;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; min-height: 100vh;
    background: radial-gradient(circle at 85% 8%, rgba(255,189,158,0.20), transparent 45%),
                linear-gradient(135deg, var(--indigo) 0%, var(--ink) 75%);
    font-family: 'Gellix','Inter',system-ui,-apple-system,'Segoe UI',sans-serif;
    color: #fff;
    padding: 48px 20px 64px;
  }}
  .wrap {{ max-width: 640px; margin: 0 auto; }}
  .eyebrow {{
    display: inline-block; font-size: 12px; letter-spacing: .04em; font-weight: 600;
    color: var(--peach); background: rgba(255,189,158,0.12);
    border: 1px solid rgba(255,189,158,0.35); border-radius: 999px;
    padding: 5px 12px; margin-bottom: 14px;
  }}
  h1 {{ font-size: 26px; font-weight: 700; margin: 0 0 8px; line-height: 1.2; }}
  .subtitle {{ color: rgba(255,255,255,0.65); font-size: 13.5px; line-height: 1.55; margin: 0 0 28px; max-width: 560px; }}
  .card {{
    background: var(--surface); color: #14122b;
    border-radius: 16px; padding: 22px 24px 24px;
    box-shadow: 0 20px 50px rgba(0,0,0,0.35);
  }}
  textarea {{
    width: 100%; min-height: 92px; font: inherit; font-size: 14.5px;
    padding: 12px 14px; border: 1.5px solid #e1def4; border-radius: 10px;
    resize: vertical; color: #14122b; background: #fff;
  }}
  textarea:focus {{ outline: none; border-color: var(--accent); }}
  .suggest-note {{ font-size: 11.5px; color: #8b87a8; margin: 6px 0 14px; min-height: 14px; }}
  .suggest-note b {{ color: var(--accent); }}
  fieldset {{ border: none; padding: 0; margin: 0 0 16px; }}
  legend {{ font-size: 11.5px; font-weight: 700; color: #8b87a8; text-transform: uppercase; letter-spacing: .04em; margin-bottom: 8px; }}
  .flag-row {{
    display: flex; align-items: center; gap: 10px; padding: 7px 4px;
    font-size: 13.5px; border-radius: 8px; cursor: pointer;
  }}
  .flag-row:hover {{ background: #f1effa; }}
  .flag-row input {{ width: 16px; height: 16px; accent-color: var(--accent); cursor: pointer; }}
  .flag-row.suggested {{ background: #f1eeff; }}
  .flag-row .tag {{
    font-size: 9.5px; font-weight: 700; color: #fff; background: var(--accent);
    border-radius: 5px; padding: 1px 5px; letter-spacing: .03em; text-transform: uppercase;
  }}
  button {{
    margin-top: 4px; padding: 11px 22px; font-size: 14px; font-weight: 650;
    color: #fff; background: var(--accent); border: none; border-radius: 10px;
    cursor: pointer; transition: transform .06s ease, box-shadow .15s ease;
    box-shadow: 0 8px 20px rgba(103,72,253,0.35);
  }}
  button:hover {{ box-shadow: 0 10px 26px rgba(103,72,253,0.5); }}
  button:active {{ transform: translateY(1px); }}
  .result {{
    margin-top: 22px; padding: 18px 20px; border-radius: 12px;
    background: linear-gradient(135deg, var(--indigo), #2b1596); color: #fff;
  }}
  .result .kicker {{ font-size: 11px; letter-spacing: .04em; text-transform: uppercase; color: var(--peach); font-weight: 700; margin-bottom: 4px; }}
  .result .model {{ font-size: 24px; font-weight: 750; }}
  .result .rules {{ color: rgba(255,255,255,0.75); font-size: 12.5px; margin-top: 8px; }}
  .ladder {{ display: flex; gap: 3px; margin-top: 14px; }}
  .seg {{
    flex: 1; text-align: center; font-size: 8.5px; padding: 6px 2px; border-radius: 5px;
    background: rgba(255,255,255,0.10); color: rgba(255,255,255,0.55);
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  }}
  .seg.active {{ background: var(--peach); color: #2b1200; font-weight: 700; }}
  footer {{ text-align: center; color: rgba(255,255,255,0.35); font-size: 11.5px; margin-top: 26px; }}
</style></head><body>
<div class="wrap">
  <span class="eyebrow">Viktor Challenge · TUM.ai</span>
  <h1>Rule-based router — live demo</h1>
  <p class="subtitle">Type a task. The starting tier reads your wording automatically — no
  checkbox needed for that part. The toggles below simulate things that happen
  <em>during</em> a task (a failure, a retry loop), which a bare prompt can't contain yet;
  checking one builds real synthetic tool-call history so the actual router code detects it —
  this isn't a mockup of the rules, it's the rules.</p>

  <div class="card">
    <form method="POST" id="f">
      <textarea name="prompt" id="prompt" placeholder="e.g. Delete the stale invoice records and confirm with finance">{prompt}</textarea>
      <div class="suggest-note" id="suggestNote">&nbsp;</div>

      <fieldset>
        <legend>What happened during the task (optional — toggle or accept a suggestion)</legend>
        {flag_rows}
      </fieldset>

      <button type="submit">Route it</button>
    </form>
    {result}
  </div>
  <footer>router.py + feature_extraction.py, unmodified — nothing here is reimplemented</footer>
</div>

<script>
// Convenience suggestions ONLY — a separate, simpler keyword scan than the real
// router rules. Never treated as the actual signal; the routing decision below
// only ever reacts to whichever boxes are checked when you submit.
const HINTS = {{
  stakes: ["delete","remove","pay","payment","publish","approve","webhook","upload","submit"],
  failed: ["error","failed","broken","not working","crash","exception"],
  retry: ["retry","stuck","keeps failing","loop","again and again"],
  reasoning: ["analyze","think through","reason about","figure out","investigate"],
  large: ["entire codebase","whole workspace","all the data","every file","comprehensive"],
  resumed_wait: ["background","waiting","poll","check back","resume"],
}};
function suggest() {{
  const text = document.getElementById('prompt').value.toLowerCase();
  const hit = [];
  for (const [flag, words] of Object.entries(HINTS)) {{
    const box = document.querySelector(`input[name="${{flag}}"]`);
    const row = box.closest('.flag-row');
    const matched = text.length > 0 && words.some(w => text.includes(w));
    row.classList.toggle('suggested', matched);
    let tag = row.querySelector('.tag');
    if (matched) {{
      box.checked = true;
      if (!tag) {{ tag = document.createElement('span'); tag.className = 'tag'; tag.textContent = 'suggested'; row.appendChild(tag); }}
      hit.push(flag);
    }} else if (tag) {{
      tag.remove();
    }}
  }}
  document.getElementById('suggestNote').innerHTML = hit.length
    ? `<b>Suggested</b> from your wording: ${{hit.join(', ')}} — review before you route.`
    : '&nbsp;';
}}
document.getElementById('prompt').addEventListener('input', suggest);
window.addEventListener('DOMContentLoaded', suggest);
</script>
</body></html>"""

def render_flag_rows(flags):
    rows = []
    for k in FLAGS:
        checked = "checked" if flags.get(k) else ""
        rows.append(
            f'<label class="flag-row"><input type="checkbox" name="{k}" {checked}>{html.escape(FLAG_LABEL[k])}</label>'
        )
    return "\n".join(rows)

class Handler(BaseHTTPRequestHandler):
    def _render(self, prompt="", flags=None, result_html=""):
        flags = flags or {}
        body = PAGE.format(
            prompt=html.escape(prompt),
            flag_rows=render_flag_rows(flags),
            result=result_html,
        )
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(body.encode())

    def do_GET(self):
        self._render()

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        data = parse_qs(self.rfile.read(length).decode())
        prompt = data.get("prompt", [""])[0]
        flags = {k: (k in data) for k in FLAGS}
        result_html = ""
        if prompt.strip():
            model, rules = route(prompt, **flags)
            idx = LADDER.index(model)
            segs = "\n".join(
                f'<div class="seg{" active" if m == model else ""}">{html.escape(m)}</div>'
                for m in LADDER
            )
            result_html = f"""<div class="result">
              <div class="kicker">Router picks</div>
              <div class="model">{html.escape(model)}</div>
              <div class="rules">rules fired: {html.escape(', '.join(rules)) or '(none — default tier)'}</div>
              <div class="ladder">{segs}</div>
            </div>"""
        self._render(prompt, flags, result_html)

    def log_message(self, fmt, *args):
        pass  # keep the console quiet

def main():
    print(f"Router demo running at http://localhost:{PORT} (Ctrl+C to stop)")
    HTTPServer(("localhost", PORT), Handler).serve_forever()

if __name__ == "__main__":
    main()
